### ISSUE TITLE
Athena IAM permissions changed massively

### ISSUE THREAD

**Issue by ashemedai** [PacktPublishing/Serverless-Analytics-with-Amazon-Athena#2]
Just encountered this repo by doing a GitHub search and wanted to let you know that various `athena:` IAM permissions seen in at least chapter 3 do not exist anymore.

E.g. `athena:GetExecutionEngine`, `athena:GetExecutionEngines`, `athena:GetNamespace`, `athena:GetCatalogs`, `athena:GetNamespaces`, `athena:GetTables`, `athena:GetTable`.

**Comment by rajat-packt** [comment]
Hey @ashemedai, thanks for sharing this with us. 
Since it has been nearly 2 years since the publishing of this title, a lot of things have changed and are now different from the content that was published. As such we are planning for the 2nd edition for this title, so please stay tuned for it! 

Closing this issue since it was out of the scope of the book when it was published.
